version: "3.8"
services:
  app:
    build:
      context: .
      target: production
    image: todo-app:production
    ports:
      - 3010:3000
    env_file:
      - .env
    environment:
      POSTGRES_USER: $PROD_USER
      POSTGRES_DB: $PROD_DB
      POSTGRES_PASSWORD: $PROD_PASSWORD
      POSTGRES_HOST: $PROD_HOST
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - pg-prod-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: $PROD_USER
      POSTGRES_DB: $PROD_DB
      POSTGRES_PASSWORD: $PROD_PASSWORD
      POSTGRES_HOST: $PROD_HOST

volumes:
  pg-prod-data:
